# Constraint file sets which input/output in the VHDL code connects to which pin in FPGA.
# Three characters after PACKAGE_PIN gives the FPGA pin which is also written next to all LEDs/Switches on the board.
# The second line (IOSTANDARD LVCMOS33) sets the voltage standard for the pins which is constant and always the same for BASYS3.

set_property PACKAGE_PIN V17 [get_ports {A[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property PACKAGE_PIN V16 [get_ports {A[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property PACKAGE_PIN W16 [get_ports {A[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property PACKAGE_PIN W17 [get_ports {A[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property PACKAGE_PIN W15 [get_ports {B[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property PACKAGE_PIN V15 [get_ports {B[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property PACKAGE_PIN W14 [get_ports {B[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property PACKAGE_PIN W13 [get_ports {B[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property PACKAGE_PIN W15 [get_ports {Opcode[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Opcode[0]}]
set_property PACKAGE_PIN V15 [get_ports {Opcode[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Opcode[1]}]
set_property PACKAGE_PIN W14 [get_ports {Opcode[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Opcode[2]}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {Result[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Result[0]}]
set_property PACKAGE_PIN E19 [get_ports {Result[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Result[1]}]
set_property PACKAGE_PIN U19 [get_ports {Result[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Result[2]}]
set_property PACKAGE_PIN V19 [get_ports {Result[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Result[3]}]
set_property PACKAGE_PIN W18 [get_ports {Carry}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {Carry}]
